#!/bin/ksh
#

${SCR_DBG}set -xv
set  -vx

SCR_NAME=mkCMATL103
SCR_PARM=1
SCR_LIST="FILE_IN"
SCR_VERS=210629.0


if [ `expr $#` -lt $SCR_PARM ]; then
   echo "Usage: $SCR_NAME ${SCR_LIST}\007"
   exit 101
fi

DateTime=`date '+DATE: %m/%d/%y  TIME: %H:%M:%S'`

echo " # "
echo " #  $SCR_NAME $* "
echo " # "
echo " #  Version $SCR_VERS "
echo " # "
echo " #  Run Date $DateTime "
echo " # "


##########################
#
#  mkCMATL103
#
##########################

#                                                                       


FILE_IN=${1:-L12emt_merge_list}


while read arc emat1 emat2 ematN   
do

mkdir $$
cd $$

cat > filelist <<EOF
 61 /nobackup/mkuzmicz/REPRO/GISL1/emat/$STAGE/$CASE/v${SNX_VER}/$arc.$SUF
 #62 /nobackup/mkuzmicz/REPRO/GISL2/emat/$STAGE/$CASE/v${SNX_VER}/$arc.$SUF
EOF

ls -la /nobackup/mkuzmicz/REPRO/GISL1/emat/$STAGE/$CASE/$arc.$SUF
#ls -la /nobackup/mkuzmicz/REPRO/GISL2/emat/$STAGE/$CASE/$arc.$SUF

RDATE=`date +%y%m%d`

#
#  SOLVE CONTROL RECORDS :
#  

cat >slvin<<EOF                                                         
TITLE  20EDT2  $sat Year $Y  ($RDATE)  cmat${sat}_$Y$V                        
                                                                        
NEWLAB 1
APRINT       12                                                         
CPRINT       11                                                         
CSTAT     1   1        .9                                               
EDIT       21  1                                                        
*PUNCH     0000200000    0    0    0.000000000000000E+00    0.000000000000000E+00
GEOID                          6378136.3               298.257          
PROCES      1     1                                                     
*PROCES    00000304100140000060   786432.000000000000000        0.000000000000000
DATA   2                                                                
CMATRIX    $ematN$N$Y$V.                    1                           
*MNSHFRNG     00000000010000.  50000000000000.
*ARCLAB       00000000010000.  50000000000000.
*MADRNG       40000000000000.  50000000000000.
*ARCLAB       85000000000000.  86000000000000.
*MADRNG       85000000000000.  86000000000000.
EOF
#


#

cat >> slvin <<EOF
MATRIX   $emat1.  61 L1          1.0000000000000 1       40000000000000.
END                                                                     
EOF
 
# MATRIX   $emat2.  62 L2          1.0000000000000 1       40000000000000.

/bin/grep CMATRIX slvin > cmtxtmp
read adum cmtnumb cdum < cmtxtmp
echo $cmtnumb > $MAIN_PATH/INFILES/$STAGE/CURRENT_L12_CMAT_NO.${V}_$ARC

#
#  SATELLITE LIST :
#
cat $MAIN_PATH/INFILES/unit1             >                                satids                                      
##

#
#  Run SOLVE II
#
time  /nobackup/mkuzmicz/EXECUTABLES/V+solve_G.x  <slvin 1>slvft6 2>errout                     


cat errout                                                              

mkdir -p /nobackup/mkuzmicz/REPRO/GISLV/emat/$STAGE/${CASE}/${PCASE}

sum cmat > sum_out
read chcksm blks fname < sum_out
if [ "$blks" -lt "50000" ]; then

  echo "Error with mkCMATLC03.${CASE}.$STAGE.${arc}" > 2mail
  mail -m mkCMATL103 -t magdak@umbc.edu < 2mail

fi

#mv cmat /umbc/epavlis/data01/LOCAL/magdak/REPRO/GISLV/emat/$STAGE/$CASE/${arc}.$V
mv cmat /nobackup/mkuzmicz/REPRO/GISLV/emat/$STAGE/v${SNX_VER}/${arc}.$V
#mv cmat /nobackup/mkuzmicz/REPRO/GISLV/emat/$STAGE/${arc}.$V
##mv cmat /raid2/REPRO/GISLV/emat/$STAGE/NASA_2003_n-2/${arc}.$V

cat summary                                                              
cat slvft6                                                              
#ls -l                                                                   
#                                                                       
cd ..
#\rm -R $$

done < $MAIN_PATH/INFILES/$FILE_IN


#echo "Done with mkCMATLC03.${CASE}.$STAGE.${Y}" > 2mail

#mail -m mkCMATLC03 -t magdak@umbc.edu < 2mail


exit 0
